### ISSUE TITLE
滾動到底自動載入

### ISSUE THREAD

**Issue by eternnoir** [rickychien/comiz#32]
在首頁時，當頁面滾動到底自動載入未載入的漫畫清單

**Comment by rickychien** [comment]
After discussion on telegram, we're not going to deliver this feature since it would involve too many UX design issue ex: how to reduce comics when there are too many comics loaded in order to avoid performance problem, how to eliminate these unseen comics to improve performance.

However, we think it's not worth to have this feature that would involve too many UX issue.
